name: 'pr-size-labeler'
description: 'Label PR using the size'
inputs:
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true
  xs-size-max:
    description: 'max size for PR to be considerated xs'
    default: '10'
    required: false
  s-size-max:
    description: 'max size for PR to be considerated s'
    default: '100'
    required: false
  m-size-max:
    description: 'max size for PR to be considerated m'
    default: '500'
    required: false
  l-size-max:
    description: 'max size for PR to be considerated m'
    default: '1000'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    -  ${{ inputs.GITHUB_TOKEN }}
    -  ${{ inputs.xs-size-max }}
    -  ${{ inputs.s-size-max }}
    -  ${{ inputs.m-size-max }}
    -  ${{ inputs.l-size-max }}